version: '3.8'

services:
  api:
    build:
      context: ./Backend/API
    volumes:
      - ./Backend/API:/app
      - node_modules_api:/app/node_modules  # Named volume for node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/API/.env
    environment:
      - NODE_ENV=development
    command: npm start

  imageprocessing:
    build:
      context: ./Backend/ImageProcessing
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./Backend/ImageProcessing/processedTracks:/app/processedTracks  # Add this line
    command: python TrackProcessor.py
    depends_on:
      - api  # Waits for api service to start

  racelineoptimizer:
    build:
      context: ./Backend/RacelineOptimizer
    volumes:
      - ./Backend/RacelineOptimizer/Input:/app/Input
      - ./Backend/RacelineOptimizer/Output:/app/Output
    command: ["dotnet", "RacelineOptimizer.dll"]
    depends_on:
      - api  # Waits for api service to start

# Define named volumes here
volumes:
  node_modules:
  node_modules_api:

  # node_frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "3000:3000"
  #   command: npm start