version: '3.8'

services:
  api:
    build:
      context: ./Backend/API
    volumes:
      - ./Backend/API:/app
      - /app/node_modules  # Prevents overwriting node_modules inside the container
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/API/.env
    environment:
      - NODE_ENV=development
    command: npm start

  imageprocessing:
    build:
      context: ./Backend/ImageProcessing
    command: python TrackProcessor.py


  # imageprocessing:
  #   build:
  #     context: ./Backend/ImageProcessing
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #   command: python TrackProcessor.py

  # node_frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - "3000:3000"
  #   command: npm start