name: C# Linting and Formatting

on:
  pull_request:
    branches: [main, dev]

permissions:
  contents: write
  pull-requests: write

jobs:
  run-linters:
    name: Run linters and formatters
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Install CSharpier (C# formatter)
        run: |
          dotnet tool install -g csharpier

      - name: Auto-format C# code with CSharpier
        run: |
          # Add .NET tools to PATH
          export PATH="$PATH:/root/.dotnet/tools"
          
          # Format Unity directory using CSharpier
          echo "🎨 Formatting C# files with CSharpier..."
          csharpier format Unity/ || echo "Some files may not have been formatted"
          echo "✅ C# formatting completed"

      - name: Commit formatting changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Unity/
          if ! git diff --staged --quiet; then
            git commit -m "Auto-format C# code with CSharpier"
            # Only push in real GitHub Actions environment, not in act
            if [ "$GITHUB_ACTIONS" = "true" ]; then
              # Push to the current branch (handles detached HEAD in GitHub Actions)
              git push origin HEAD:${{ github.head_ref || github.ref_name }}
            else
              echo "Skipping push in local test environment"
            fi
          else
            echo "No formatting changes to commit"
          fi