name: C# Linting

on:
  pull_request:
    branches:
      - dev

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Generate Unity project files
        run: |
          # Check if Unity directory exists
          if [ -d "Unity" ]; then
            echo "Unity directory found"
            # List contents to see what's actually there
            ls -la Unity/
          else
            echo "Unity directory not found, checking for Unity scripts in other locations"
            find . -name "*.cs" -type f | head -10
          fi

      - name: Run C# linting with file-based approach
        uses: wearerequired/lint-action@v2
        with:
          dotnet_format: true
          dotnet_format_args: "--include **/*.cs --verify-no-changes"